### ISSUE TITLE
Update CodeQL Action to v3

### ISSUE THREAD

**Issue by fortifysoftware** [fortify/github-action#32]
The following warning is issued when exporting results to the GitHub Security Code Scanning dashboard:

> **Warning:** CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

**Comment by rsenden** [comment]
Hi @fortifysoftware, I just pushed a commit to use v3 of the upload-sarif action, can you please retest with `fortify/github-action@main` to confirm the deprecation warning is now removed? I'll then publish a new release.

**Comment by fortifysoftware** [comment]
Looks good! No more warning. Thank you. 👍🏻

**Comment by rsenden** [comment]
Fixed in 1.2.2
