### ISSUE TITLE
Is it possible to use git actions for create automatically version on Fortify SSC server?

### ISSUE THREAD

**Issue by ashokvaddevalli** [fortify/github-action#36]
In Jenkins i am able to create automatically version using fortify upload plugin and also working using jenkins pipeline.

**Comment by rsenden** [comment]
Not yet, but we plan on adding this functionality within the next 1-2 months or so.

**Comment by ashokvaddevalli** [comment]
> Not yet, but we plan on adding this functionality within the next 1-2 months or so.

What about using Fortify cli automatically create version? is it possible?

**Comment by rsenden** [comment]
> > Not yet, but we plan on adding this functionality within the next 1-2 months or so.
> 
> What about using Fortify cli automatically create version? is it possible?

Yes, that's certainly possible: https://fortify.github.io/fcli/v2.4.0/manpage/fcli-ssc-appversion-create.html. This command also has partial support for copying existing application versions; there's PR https://github.com/fortify/fcli/pull/483 to allow for also copying user access and other settings but this still needs some review. Once complete, we'll integrate the functionality for creating and copying application versions into the GitHub Action.

In case you were not aware yet, you can install fcli during pipeline execution using the `fortify/github-action/setup` action.
